[application]
geng = "0.6.0 <= v < 0.7.0"
runtime = "node"
source-directories = ["src"]

[dependencies]
"github.com/gilramir/gren-argparse" = "2.0.0 <= v < 3.0.0"
"github.com/geng-language/node" = "6.1.0 <= v < 7.0.0"
"github.com/geng-language/stream" = "0.1.0 <= v < 0.2.0"

[sources]
"github.com/gilramir/gren-argparse" = { path = "../.." }
"github.com/geng-language/node" = { path = "../../../../gren-lang/node" }
"github.com/geng-language/stream" = { path = "../../../../../packages/stream" }
"github.com/geng-language/url" = { path = "../../../../../packages/url" }
